### ISSUE TITLE
Different syntax for evaluator output

### ISSUE THREAD

**Issue by fearoffish** [jaspervdj/patat#187]
When I evaluate a code block, I want the output to be in a code block of a different syntax.

Slide config:

```yaml
slideLevel: 2
wrap: false
margins:
  left: 10
  top: 5
incrementalLists: true
tabStop: 2
eval:
  ruby:
    command: irb --noecho --noverbose
    container: none
```

In my slide:

```ruby
def positional_args(x, y)
  puts "W00T!"
  puts "x: #{x}, y: #{y}"
end

positional_args(1, 2)
```

The output assumes a syntax of `ruby`, but I just want plain (or maybe something else). I've tried `code`, `inline` and `none` but none behave as I need. 

Screenshots of behaviour:

code:
![Image](https://github.com/user-attachments/assets/0e08d5c9-0797-45cc-a1d7-942215dfbdd7)

inline:
![Image](https://github.com/user-attachments/assets/f6acdd9e-8cdc-4412-9665-29d4900dca29)

none:
![Image](https://github.com/user-attachments/assets/f293f5e4-0be4-4b25-accf-8fcc2afaecea)

Side note: The indentation on the output is wrong too, if I run the code manually they are flush with the left terminal but patat is adding whitespace to the first line of output.

**Comment by jaspervdj** [comment]
Thanks for reporting this issue!

Right-- currently the eval (wrongly) assumes the output should be highlighted the same was as the input.  We can't really know what format the output will be in, so I think we should go ahead with just adding another setting for this, e.g.:


```
eval:
  ruby:
    command: irb --noecho --noverbose
    container: none
    classes: ["json"] # classes to set on the output
```

This should be a relatively easy task.  Feel free to suggest other names... maybe `classes` is to generic but `syntax` is to specific.

---

I wasn't able to reproduce the other issue (yet): for me `W00T!` has the correct indentation, with the settings you provided.  Can I get some more info for this (mostly to eliminate possible causes):

1. Which patat version are you using?
2. Which terminal emulator are you using?
3. Does this problem also occur if you don't set `margins`?
4. Can you confirm `irb` works correct, e.g. the output of this command:

    ```
    irb --noecho --noverbose <script.rb | od -c
    ```

    Should start with `W` and no weird whitespace characters.
