### ISSUE TITLE
How can I "theme" an eval code block?

### ISSUE THREAD

**Issue by halloleo** [jaspervdj/patat#191]
Firstly, thanks heaps for `patat`. It's a great tool for terminal slides!

I am using figlet for some title slides:

    ---
    patat:
      theme:
        codeBlock: [vividBlue, bold]
      eval:
        figletTitle:
          command: figlet -k -f big
          reveal: false
          replace: true
    ...
    
    ```figletTitle
    What is Xonsh?
    ```
    
This code block is then rendered with the theming for code blocks (`vividBlue`), however I want these title in `vividRed`, so I do:

    
    ```figletTitle
    What is Xonsh?
    ```

This is _a little bit_ cumbersome. Is there a way to set for `figletTitle` code blocks another theme than for real-code code blocks?

**Comment by jaspervdj** [comment]
Sidenote: I was trying to reproduce this but couldn't.  It seems like recent pandoc releases are downcasing code block classes (e.g. it's looking for `figlettitle`).  I will fix that separately.

Back to the issue: there's currently no way to do this, but I think it's a good idea.  It could look something like:

```
theme:
    codeBlock:
      default: [vividBlue]
      figletTitle: [vividRed]
```

A workaround for now could be to use an additional command (e.g. `awk`) -- this seems to work:

    ---
    patat:
      eval:
        figlet:
          command: figlet | awk '{print "    \033[32m" $0 "\033[0m"}'
          reveal: false
          replace: true
          container: inline
    ...

    ```figlet
    What is Xonsh?
    ```

**Comment by halloleo** [comment]
> Sidenote: I was trying to reproduce this but couldn't. It seems like recent pandoc releases are downcasing code block classes (e.g. it's looking for `figlettitle`). I will fix that separately.

Yes, I noticed the same - keeping the eval classes lowercase is an easy workaround.

> ```
> theme:
>     codeBlock:
>       default: [vividBlue]
>       figletTitle: [vividRed]
> ```

What would be a great way to do it.  😄 

> A workaround for now could be to use an additional command (e.g. `awk`) -- this seems to work:
> ...

Makes sense. I will try this.

**Comment by halloleo** [comment]
> A workaround for now could be to use an additional command (e.g. `awk`) -- this seems to work:
> 
>     ---
>     patat:
>       eval:
>         figlet:
>           command: figlet | awk '{print "    \033[32m" $0 "\033[0m"}'
>           reveal: false
>           replace: true
>           container: inline
>     ...
>     
>     ```figlet
>     What is Xonsh?
>     ```

**Now I have tried the `awk` hack.**

However for me it doesn't fully work. Three problems:

1. The first line in the output is moved a few characters to the right:

    ![Image](https://github.com/user-attachments/assets/9e4d869b-5801-4a2e-b004-b23a12d9e5ea)

2. I use the `dissolve` transition. Then during the transition the escaped characters are shown briefly in plain (i.e. escaped).

4.  The presentation starts hanging after a few back-and-forth slide changes with a screen like this:

    ![Image](https://github.com/user-attachments/assets/4c53ba4f-7d6b-4832-8dcb-c4fec78267a7)

    Only multiple Ctrl-C can get me out of it.

I think the `inline` container doesn't work perfectly. -- **Is there a way to see better what patat behind the scenes does?**

***

Just in case the issues are related to my config:

A. Here the full YAML header:

```
---
title: '_'
patat:
  wrap: 60
  margins: 
    left: auto
    right: auto
  slideLevel: 1
  transition:
    type: dissolve
    duration: 0.3
  theme:
    emph: [vividBlack, italic]
    strong: [vividBlack, onDullWhite]
    header: [vividWhite, onVividBlack, italic]
    codeBlock: [vividBlue]
  eval:
    figlet:
      command: figlet | awk '{print "    \033[32m" $0 "\033[0m"}'
      reveal: false
      replace: true
      container: inline
...
```

B. Here my environment:

* OS: **macOS**
* Terminal: **iTerm2**
* patat version: **0.15.0.0 Using pandoc: 3.6.4**
