### ISSUE TITLE
Bullet markers escaping rules / enforce literate parsing

### ISSUE THREAD

**Issue by amerlyq** [jaspervdj/patat#30]
Consider next inline header:
```yaml
patat:
    theme:
        bulletListMarkers: '<>'
```
Markers must be treated literally (or at least clarify escaping rules).
Because when rendering: `'-*'` becomes `'-\'`, `'<>'` becomes `'&l'` and `'><'` becomes `'> '`
