### ISSUE TITLE
Proposal: custom renderers

### ISSUE THREAD

**Issue by Tenchi2xh** [jaspervdj/patat#52]
It's kind of a crazy idea, but after thinking for a while about how to manage this in the settings, I think I got a simple solution in the end.

It's a bit long to explain so I'll let the images do the talking:

<img width="962" alt="screen shot 2018-08-27 at 23 45 36" src="https://user-images.githubusercontent.com/4116708/44688111-84b10000-aa53-11e8-8f83-5567eeaca1ad.png">
<img width="962" alt="screen shot 2018-08-27 at 23 45 41 1" src="https://user-images.githubusercontent.com/4116708/44688112-84b10000-aa53-11e8-97b4-63de841622af.png">
<img width="962" alt="screen shot 2018-08-27 at 23 45 44" src="https://user-images.githubusercontent.com/4116708/44688113-84b10000-aa53-11e8-9bde-d0924d64c9d1.png">
<img width="962" alt="screen shot 2018-08-27 at 23 54 28" src="https://user-images.githubusercontent.com/4116708/44688458-9d6de580-aa54-11e8-85e2-3d23271e5f51.png">
<img width="962" alt="screen shot 2018-08-27 at 23 54 30" src="https://user-images.githubusercontent.com/4116708/44688459-9e067c00-aa54-11e8-9a82-381911f4b4c4.png">
<img width="962" alt="screen shot 2018-08-27 at 23 54 32" src="https://user-images.githubusercontent.com/4116708/44688460-9e067c00-aa54-11e8-9650-c77865357a92.png">
<img width="962" alt="screen shot 2018-08-27 at 23 54 35" src="https://user-images.githubusercontent.com/4116708/44688462-9e067c00-aa54-11e8-8c9b-0cfb44047811.png">
<img width="962" alt="screen shot 2018-08-27 at 23 54 37" src="https://user-images.githubusercontent.com/4116708/44688463-9e067c00-aa54-11e8-8f39-442770cd2034.png">

What do you think? It would make it much easier for including diagrams. The alternative, inlining all diagrams and ASCII art, would take a lot of space in the markdown file, and make it harder to maintain: lots compiling, copy-pasting, and escaping special characters.

Here's in text format the config format I showed in the screenshots above:

```yaml
imageRenderers:
  - pattern: .*\.(monopic|mono)
    command: monodraw --unicode {0}
  - pattern: .*\.puml
    command: java -jar ~/plantuml.jar -f txt {0}

spanRenderers:
  figlet:
    parameters:
      font: -f {0}
    command: figlet {0} {1}

  toilet:
    parameters:
      font: -f {0}
      filter: -F {0}
    command: toilet {0} {1}

  rainbowCow:
    parameters:
      cowfile: -f {0}
    command: cowsay {0} {1} | lolcat -F 0.3
```
